language: node_js
node_js:
  - "10"
before_script:
- ./prebuild.sh
- gem install sass -v 3.4.25
env:
  global:
  - GH_REPO="laraconfbrasil/website"
script: docpad generate --debug --silent --env static
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    docpad deploy-ghpages --env static
